
services:
  postgres:
    image: postgres:15-alpine
    container_name: iam_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=iam_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iam-network

  redis:
    image: redis:7-alpine
    container_name: iam_redis
    ports:
      - "6379:6379"
    networks:
      - iam-network

volumes:
  postgres_data:

networks:
  iam-network:
    driver: bridge
